name: CI
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
env:
  JULIA_PKG_SERVER: https://internal.juliahub.com/
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
        os:
          - self-hosted
          # - macOS-latest
        arch:
          - x64
    steps:
      - name: Set debug env
        run: export JULIA_DEBUG="loading"
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        name: Checkout
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: "Set up private JuliaHub registries"
        uses: "JuliaComputing/set-up-private-juliahub-registries@v1.2.1"
        with:
          encoded-juliahub-token: "${{ secrets.JULIAHUB_TOKEN_ENCODED }}"
          ssh-key: "${{ secrets.JULIASIM_REGISTRY_SSH_KEY }}"
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        continue-on-error: ${{ matrix.version == '1.6' }} # Allow to fail and workflow still count as completed
